language: python
sudo: false
branches:
  only:
  - master
  - "/^\\d\\.\\d+$/"
  - "/^\\d\\.\\d+\\.\\d+(rc\\d+|\\.dev\\d+)?$/"
matrix:
  include:
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7
    env: TOXENV=py37
    dist: xenial
install:
- pip install -U tox
script: tox
after_success:
  - codecov
cache:
  directories:
  - "$HOME/.cache/pip"
